export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/notifications";
export { default as KPI } from "@/pages/dashboard/kpi";
export { default as ApplicationsListPage } from "@/pages/dashboard/applications/list";
export { default as ApplicationsEvaluationPage } from "@/pages/dashboard/applications/evaluation";
export { default as ComplexDashboardPage } from "@/pages/dashboard/complex-dashboard";
export { default as ResidentDashboard } from "@/pages/dashboard/resident-dashboard";
export { default as MtkPage } from "@/pages/dashboard/management/mtk";
export { default as ComplexesPage } from "@/pages/dashboard/management/complexes";
export { default as BuildingsPage } from "@/pages/dashboard/management/buildings";
export { default as BlocksPage } from "@/pages/dashboard/management/blocks";
export { default as ResidentsPage } from "@/pages/dashboard/management/residents";
export { default as SendNotificationPage } from "@/pages/dashboard/notifications/send";
export { default as NotificationArchivePage } from "@/pages/dashboard/notifications/archive";
export { default as SentSMSPage } from "@/pages/dashboard/notifications/sent-sms";
export { default as CreateQueryPage } from "@/pages/dashboard/queries/create";
export { default as QueriesListPage } from "@/pages/dashboard/queries/list";
export { default as ReceptionPage } from "@/pages/dashboard/reception";
export { default as ServicesPage } from "@/pages/dashboard/services";
export { default as ElectronicDocumentsPage } from "@/pages/dashboard/e-documents";
export { default as UserAddPage } from "@/pages/dashboard/users/add";