export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export { default as KPI } from "@/pages/dashboard/kpi";
export { default as ApplicationsListPage } from "@/pages/dashboard/applications/list";
export { default as ApplicationsEvaluationPage } from "@/pages/dashboard/applications/evaluation";
export * from "@/pages/dashboard/mtk";
export { default as ComplexPage } from "@/pages/dashboard/complex";
export { default as ResidentsPage } from "@/pages/dashboard/residents";
export { default as BuildingsPage } from "@/pages/dashboard/buildings";
export { default as PropertiesPage } from "@/pages/dashboard/properties";
export { default as BlocksPage } from "@/pages/dashboard/blocks";
