export const demoUsers = [
  {
    id: 1,
    username: "admin",
    password: "admin123",
    fullName: "Admin User",
    firstName: "Admin",
    lastName: "User",
    email: "admin@mail.az",
    phone: "+994 12 345 67 89",
    address: "Bakı, Nəsimi rayonu",
    birthDate: "1985-05-15",
    role: "admin",
  },
  {
    id: 2,
    username: "manager",
    password: "manager123",
    fullName: "Manager User",
    firstName: "Manager",
    lastName: "User",
    email: "manager@mail.az",
    phone: "+994 12 345 67 90",
    address: "Bakı, Yasamal rayonu",
    birthDate: "1990-08-20",
    role: "manager",
  },
  {
    id: 3,
    username: "operator",
    password: "operator123",
    fullName: "Operator User",
    firstName: "Operator",
    lastName: "User",
    email: "operator@mail.az",
    phone: "+994 12 345 67 91",
    address: "Bakı, Nərimanov rayonu",
    birthDate: "1992-03-10",
    role: "operator",
  },
  {
    id: 4,
    username: "viewer",
    password: "viewer123",
    fullName: "Viewer User",
    firstName: "Viewer",
    lastName: "User",
    email: "viewer@mail.az",
    phone: "+994 12 345 67 92",
    address: "Bakı, Səbail rayonu",
    birthDate: "1995-11-25",
    role: "viewer",
  },
  {
    id: 5,
    username: "sakin1",
    password: "sakin123",
    fullName: "Əli Məmmədov",
    firstName: "Əli",
    lastName: "Məmmədov",
    email: "ali.mammadov@mail.az",
    phone: "+994 12 345 67 93",
    address: "Bakı, Nəsimi rayonu, Məhəmməd Hadi küçəsi 15",
    birthDate: "1988-07-12",
    role: "resident",
  },
  {
    id: 6,
    username: "sakin2",
    password: "sakin123",
    fullName: "Ayşə Həsənova",
    firstName: "Ayşə",
    lastName: "Həsənova",
    email: "ayse.hasanova@mail.az",
    phone: "+994 12 345 67 94",
    address: "Bakı, Yasamal rayonu, Nizami küçəsi 25",
    birthDate: "1992-03-20",
    role: "resident",
  },
  {
    id: 7,
    username: "sakin3",
    password: "sakin123",
    fullName: "Rəşad Quliyev",
    firstName: "Rəşad",
    lastName: "Quliyev",
    email: "rashad.guliyev@mail.az",
    phone: "+994 12 345 67 95",
    address: "Bakı, Nərimanov rayonu, Azadlıq prospekti 100",
    birthDate: "1990-11-05",
    role: "resident",
  },
  {
    id: 8,
    username: "sakin4",
    password: "sakin123",
    fullName: "Leyla Əliyeva",
    firstName: "Leyla",
    lastName: "Əliyeva",
    email: "leyla.aliyeva@mail.az",
    phone: "+994 12 345 67 96",
    address: "Bakı, Səbail rayonu, İstiqlaliyyət küçəsi 50",
    birthDate: "1995-09-15",
    role: "resident",
  },
];
